#!/bin/bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}

#!/bin/bash

# Get Microphone Volume
get_volume_mic() {
	volume_mic=$(amixer -c 0 sget 'Capture' | grep -oP '\[\K[0-9]+(?=%\])' | head -n 1)
	echo "$volume_mic"
}

# Get icons
get_icon() {
	current=$(get_volume)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/volume-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$iDIR/volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/volume-mid.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$iDIR/volume-high.png"
	fi
}

# Get icons speaker ags
get_icon_ags() {
	current=$(get_volume)
	if [[ "$current" -eq "0" ]]; then
		echo 'audio-volume-low-symbolic'
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo 'audio-volume-low-symbolic'
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo 'audio-volume-medium-symbolic'
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo 'audio-volume-high-symbolic'
	fi
}

# Get icons mic ags
get_icon_ags_mic() {
	current=$(get_volume_mic)
	if [[ "$current" -eq "0" ]]; then
		echo 'microphone-sensitivity-low-symbolic'
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo 'microphone-sensitivity-low-symbolic'
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo 'microphone-sensitivity-medium-symbolic'
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo 'microphone-sensitivity-high-symbolic'
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume)"
}

# Increase Volume
inc_volume() {
	pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
	pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --source 65 --get-mute)" == "false" ]; then
		pamixer -m --source 65 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
	elif [ "$(pamixer --source 65 --get-mute)" == "true" ]; then
		pamixer -u --source 65 && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
	fi
}

# Increase Volume
inc_volume_ags() {
	ags -b hypr -r "audio.speaker.volume += 0.05; indicator.speaker()"
}

# Decrease Volume
dec_volume_ags() {
	ags -b hypr -r "audio.speaker.volume -= 0.05; indicator.speaker()"
}
# Toggle Mute
toggle_mute_ags() {
	if [ "$(ags -b hypr -r 'audio.speaker.isMuted')" == "false" ]; then
		ags -b hypr -r "audio.speaker.isMuted = true" && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "audio-volume-muted-symbolic" "Speakers Off" "Volume"
	elif [ "$(ags -b hypr -r 'audio.speaker.isMuted')" == "true" ]; then
		ags -b hypr -r "audio.speaker.isMuted = false" && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon_ags)" "Speakers On" "Volume"
	fi
}

# Toggle Mic
toggle_mic_ags() {
	if [ "$(ags -b hypr -r 'audio.microphone.isMuted')" == "false" ]; then
		ags -b hypr -r "audio.microphone.isMuted = true" && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "microphone-sensitivity-muted-symbolic" "Microphone Off" "Volume"
	elif [ "$(ags -b hypr -r 'audio.microphone.isMuted')" == "true" ]; then
		ags -b hypr -r "audio.microphone.isMuted = false" && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon_ags_mic)" "Microphone On" "Volume"
	fi
}
# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--inc-ags" ]]; then
	inc_volume_ags
elif [[ "$1" == "--dec-ags" ]]; then
	dec_volume_ags
elif [[ "$1" == "--toggle-ags" ]]; then
	toggle_mute_ags
elif [[ "$1" == "--toggle-mic-ags" ]]; then
	toggle_mic_ags
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
else
	get_volume
fi
