#!/usr/bin/bash

source /home/berz/.config/dwmblocks/scripts/theme   
## Brightness
brightness() {

  case $BLOCK_BUTTON in
    # 1) 1 dito 2) 3 dita 3) 2 dita
 	  1) gammastep -m randr -P -O 3200 ;;
 	  2) gammastep -m randr -x ;;
 	  3) xrandr --output eDP1 --brightness 0.15;;

  esac
	LIGHT=$(printf "%.0f\n" `light -G`)

	if [[ ("$LIGHT" -ge "0") && ("$LIGHT" -le "25") ]]; then
		printf "^c$YELLOW^^b$BLACK^  $LIGHT%%^d^%s"
	elif [[ ("$LIGHT" -ge "25") && ("$LIGHT" -le "50") ]]; then
		printf "^c$YELLOW^^b$BLACK^  $LIGHT%%^d^%s"
	elif [[ ("$LIGHT" -ge "50") && ("$LIGHT" -le "75") ]]; then
		printf "^c$YELLOW^^b$BLACK^  $LIGHT%%^d^%s"
	elif [[ ("$LIGHT" -ge "75") && ("$LIGHT" -le "100") ]]; then
		printf "^c$YELLOW^^b$BLACK^  $LIGHT%%^d^%s"
	fi

}
brightness
