version = "1.1.4"

[format]
dedup = true
dedup_inactive_fullscreen = true
delim = " "
client = "{icon}{delim}"
client_active = "<span color='#6f8faf'>{icon}</span>"
workspace = "{id}:<b><span color='#c7b89d'>{delim}{clients}</span></b>"
workspace_empty = "{id}:<b><span color='#5d6061'>{delim}{clients}</span></b>"
client_dup = "{icon} {counter_sup}{delim}"
client_dup_fullscreen = "{icon} {counter_sup}{delim}"
client_fullscreen = "{icon}{delim}"

[class_active]
# DEFAULT="<span color='#89b4fa'>{icon}</span>"
# "(?i)firefox" = "<span color='orange'></span>"
# "(?i)foot" = "<span color='#cba6f7'></span>"
# "(?i)wofi" = ""

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[initial_title_in_class."kitty"]
"zsh" = "Zsh"

[title_in_class."(firefox|chrom.*)"]
"(?i)youtube" = "ꟳ"
"(?i)twitch" = "ꟳ"

[title_active."(firefox|chrom.*)"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

[workspaces_name]
0 = ""
1 = ""
2 = ""
3 = ""
4 = ""
5 = ""
6 = ""
7 = ""
8 = ""
9 = ""
10= ""
[exclude]
"(?i)wofi" = ".*" # will match all title for wofi

[class]
DEFAULT = ""
"(?i)firefox" = ""
"(?i)kitty" = ""
"(?i)foot" = ""
"(?i)alacritty" = ""
bleachbit = ""
burp-startburp = ""
calibre-gui = ""
"chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default" = ""
chromium = ""
"Gimp-2.10" = ""
code-oss = ""
cssh = ""
darktable = ""
discord = ""
dmenu-clipboard = ""
dmenu-pass = ""
duolingo = ""
element = ""
evince = ""
fontforge = ""
gcr-prompter = ""
gnome-pomodoro = ""
gsimplecalc = ""
"jetbrains-studio" = ""
"kak" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
obsidian = ""
"dmenu-emoji" = ""
"dmenu-browser" = ""
"dmenu-pass generator" = ""
"qalculate-gtk" = ""
krita = ""
libreoffice-calc = ""
libreoffice-impress = ""
libreoffice-startcenter = ""
libreoffice-writer = ""
molotov = ""
mpv = ""
neomutt = ""
nm-connection-editor = ""
org-ksnip-ksnip = ""
"org.pwmt.zathura" = ""
"org.inkscape.Inkscape" = ""
org-qutebrowser-qutebrowser = ""
org-telegram-desktop = ""
paperwork = ""
pavucontrol = ""
personal = ""
plexamp = ""
qutepreview = ""
rapid-photo-downloader = ""
remote-viewer = ""
sandboxed-tor-browser = ""
scli = ""
shopping = ""
Signal = ""
slack = ""
snappergui = ""
songrec = ""
Spotify = ""
steam = ""
streamlink-twitch-gui = ""
sun-awt-x11-xframepeer = ""
swappy = ""
taskwarrior-tui = ""
"org.telegram.desktop" = ""
thunderbird = ""
thunar = ""
".*transmission.*" = ""
udiskie = ""
vimiv = ""
virt-manager = ""
vlc = ""
vncviewer = ""
wayvnc = "󰀄"
whatsapp-desktop = ""
whatsapp-nativefier-d52542 = ""
wire = "󰁀"
wireshark-gtk = ""
wlfreerdp = "󰀄"
work = ""
xplr = ""
nemo = ""
zoom = ""
