#!/bin/bash

# CONFIG_FILES="$HOME/.config/waybar/config.jsonc $HOME/.config/waybar/style.css"
CONFIG_FILES="/home/berz/GIT/waybar_cool/dots/.config/waybar/config.jsonc /home/berz/GIT/waybar_cool/dots/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
	waybar -c /home/berz/GIT/waybar_cool/dots/.config/waybar/config.jsonc -s /home/berz/GIT/waybar_cool/dots/.config/waybar/style.css &
	inotifywait -e create,modify $CONFIG_FILES
	killall waybar
done
